spring:
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:5432/wallet
    username: wallet
    password: wallet
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
        hibernate:
          format_sql: false
          dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080
