version: '3'

services:
  postgres:
    image: postgres
    volumes:
      - ../scripts/development/postgres/create-table-test-schema.sql:/docker-entrypoint-initdb.d/create-tables.sql
    environment:
      POSTGRES_USER: "wallet"
      POSTGRES_PASSWORD: "wallet"
      POSTGRES_DB: "wallet"
    ports:
      - "5432:5432"

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      - kafka-net
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://localhost:9092,OUTSIDE://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_CREATE_TOPICS: "wallet-transactions:1:1"
    networks:
      - kafka-net
  redis:
    image: redis
    ports:
      - "6379:6379"

networks:
  kafka-net:
    driver: bridge
